apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: jahid
  region: us-east-1

iam:
  withOIDC: true

addons:
  - name: aws-ebs-csi-driver
    version: "latest"
    wellKnownPolicies:      # add IAM and service account
      ebsCSIController: true
  - name: vpc-cni
    version: "latest"
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  - name: coredns
    version: "latest"  # Specify a fixed version if you require stability.
  - name: kube-proxy
    version: "latest"  # Specify a fixed version if you require stability.

managedNodeGroups:
  - name: mg-1
    instanceType: t2.medium
    desiredCapacity: 4
    minSize: 2
    maxSize: 5
    volumeSize: 20  # You can adjust the disk size as needed
    iam:
      withAddonPolicies:
        ebs: true
