apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: jahid
  region: us-east-1

iam:
  withOIDC: true

addons:
  - name: aws-ebs-csi-driver
    version: latest
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_EBS_CSI_Driver_Policy
  - name: vpc-cni
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest

nodeGroups:
  - name: ng-1
    instanceType: t2.medium
    desiredCapacity: 4
    iam:
      withAddonPolicies:
        ebs: true
