pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh'''
                    echo "Building docker image..."
                    docker build -t ecom-back:v3 .
                    docker tag ecom-back:v3 transformation2/ecom-back:v$BUILD_NUMBER
                '''
            }
        }
        stage('Push') {
            steps {
                sh'''
                    echo "Pushing docker image into Dockerhub..."
                    docker push transformation2/ecom-back:v$BUILD_NUMBER 
                '''
            }
        }
        stage('Deploy') {
            steps {
                sh'''
                    echo "Deploying into swarm new..."
                    ssh ubuntu@3.93.213.255 docker service update --image transformation2/ecom-back:v$BUILD_NUMBER products_ecom-back
                '''
            }
        }
}
}
